spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sgsecurity?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 1q2w3e
server:
  port: 8880

# 配置mybatisplus
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
#  type-aliases-package: com.xiaobai.entity.pojo